#!/bin/bash

# Configuration
# BUCKET_NAME=bloodcancer_model_bucket
# BUCKET=gs://bloodcancer_model_bucket/

# # Compute Engine
# INSTANCE=instance-20250304-174844

# # ML Flow
# MLFLOW_TRACKING_URI=https://mlflow.lewagon.ai
# MLFLOW_EXPERIMENT=bloodcancer
# MLFLOW_MODEL_NAME=bloodcancer

# # Train params
# BATCH_SIZE=32
# EPOCHS=1
# VALIDATION_SPLIT=0.3
# TEST_SPLIT=0.1

# # Production model
# PRODUCTION_MODEL_NAME=20250314-005854.keras
# EVALUATION_MODEL_NAME=20250314-005854.keras

# GCP_PROJECT_ID=reverberant-yew-448413-i1
# DOCKER_IMAGE_NAME=leuk_detect_docker_image
# GCP_REGION=europe-west10
# DOCKER_REPO_NAME=leuk-detect-repo
# PORT=8080

ENV_VARS="BUCKET_NAME=$BUCKET_NAME,BUCKET=$BUCKET,INSTANCE=$INSTANCE,MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI,MLFLOW_EXPERIMENT=$MLFLOW_EXPERIMENT,MLFLOW_MODEL_NAME=$MLFLOW_MODEL_NAME,BATCH_SIZE=$BATCH_SIZE,EPOCHS=$EPOCHS,VALIDATION_SPLIT=$VALIDATION_SPLIT,TEST_SPLIT=$TEST_SPLIT,LOCAL_MODEL_PATH=$LOCAL_MODEL_PATH,PRODUCTION_MODEL_NAME=$PRODUCTION_MODEL_NAME,EVALUATION_MODEL_NAME=$EVALUATION_MODEL_NAME,GCP_PROJECT_ID=$GCP_PROJECT_ID,DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME,GCP_REGION=$GCP_REGION,DOCKER_REPO_NAME=$DOCKER_REPO_NAME"

docker build --platform linux/amd64 -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:0.1 .

docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:0.1

gcloud run deploy --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:0.1 --region $GCP_REGION --memory=2Gi --set-env-vars $ENV_VARS
